#!/bin/bash

#cp -f ~/openwrt/bin/targets/x86/64/packages/* ~/openwrt/bin/packages/x86_64/custom

SCRIPT=openwrt/scripts/ipkg-make-index.sh
export PATH="openwrt/staging_dir/host/bin:$PATH"
# Generates package manifest
cp openwrt/addon/* openwrt/bin/packages/*/custom/
cd openwrt/bin/packages/*/custom
$SCRIPT . 2>/dev/null > Packages.manifest
grep -vE '^(Maintainer|LicenseFiles|Source|Require)' Packages.manifest > Packages
sed -i ":a;$!N;s/Package: aria2\nVersion: ./Package: aria2\nVersion: 9/g;ba" Packages
sed -i ":a;$!N;s/Package: netdata\nVersion: ./Package: netdata\nVersion: 9/g;ba" Packages
sed -i ":a;$!N;s/Package: smartdns\nVersion: ./Package: smartdns\nVersion: 9/g;ba" Packages
gzip -9nc Packages > Packages.gz
cd -
cd openwrt/bin/targets/x86/64/packages
# wget -r -nH -np --reject="index.html*" --cut-dirs=7 https://mirrors.cloud.tencent.com/openwrt/snapshots/targets/x86/64/packages
$SCRIPT . 2>/dev/null > Packages.manifest
grep -vE '^(Maintainer|LicenseFiles|Source|Require)' Packages.manifest > Packages
# sed -i 's/ kernel (=.*)\(,\|$\)//g' Packages
gzip -9nc Packages > Packages.gz
cd -
/usr/bin/sshpass -p Gary139715 scp -r openwrt/packages/* root@8.210.171.109:/data/wwwroot/op.supes.top/x64/luci/
#/usr/bin/sshpass -p 139715jia scp -r ~/openwrt/bin/packages/x86_64/custom/* root@10.0.0.1:/data/www/openwrt/x64/luci/
#/usr/bin/sshpass -p 139715jia scp -r ~/openwrt/bin/targets/x86/64/packages/* root@10.0.0.1:/data/www/openwrt/x64/kmod/
