#!/bin/bash

#cp -f ~/openwrt/bin/targets/x86/64/packages/* ~/openwrt/bin/packages/x86_64/custom

SCRIPT=${GITHUB_WORKSPACE}/openwrt/scripts/ipkg-make-index.sh
export PATH="${GITHUB_WORKSPACE}/openwrt/staging_dir/host/bin:$PATH"
# Generates package manifest
cd ${GITHUB_WORKSPACE}/packages
$SCRIPT . 2>/dev/null > Packages.manifest
grep -vE '^(Maintainer|LicenseFiles|Source|Require)' Packages.manifest > Packages
sed -i ":a;$!N;s/Package: aria2\nVersion: ./Package: aria2\nVersion: 9/g;ba" Packages
sed -i ":a;$!N;s/Package: netdata\nVersion: ./Package: netdata\nVersion: 9/g;ba" Packages
sed -i ":a;$!N;s/Package: smartdns\nVersion: ./Package: smartdns\nVersion: 9/g;ba" Packages
sed -i ":a;$!N;s/Package: mwan3\nVersion: ./Package: mwan3\nVersion: 9/g;ba" Packages
gzip -9nc Packages > Packages.gz
cd -
